name: siege-bridge
version: '${project.version}'
main: org.oreo.siegebridge.Siege_bridge
api-version: '1.20'


commands:
  siege-bridge: #Give the siege bridge to the player
    description: Gives a siegebridge to the player
    usage: /<command>
    aliases: [siege-bridge]